sudo: required
dist: trusty
language: minimal

services:
  - docker

branches:
  only:
    - master

cache:
  directories:
    - .terraform

script:
  - ./bin/terraform init -input=false
  - ./bin/terraform validate -check-variables=false .
  - if [[ -n "$(./bin/terraform fmt -write=false)" ]]; then echo "Some terraform files need be formatted, run 'terraform fmt' to fix"; exit 1; fi
  - ./bin/tflint --debug

notifications:
  email: false
